teste

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -41,9 +41,9 @@ jobs:
     - name: Validate test results
        run: |
          if [ $? -ne 0 ]; then
-          echo "Test run failed. Exiting..."
-          exit 1
-        fi 
+           echo "Test run failed. Exiting..."
+           exit 1
+         fi 
 
     - name: Upload code coverage result
       uses: codecov/codecov-action@v3
